# nodejsDockerfile/Dockerfile

# Usando uma imagem base do Node.js
FROM node:lts-hydrogen

# Definindo o diretório de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Expondo a porta que o app Node.js usará
EXPOSE 3000
